# Generated by Django 5.2.8 on 2025-11-09 07:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('schema_json', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='tenants.environment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='tenants.organization')),
            ],
            options={
                'db_table': 'tools_tool',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'environment', 'name', 'version')},
            },
        ),
    ]
