# Generated by Django 5.2.8 on 2025-11-09 07:42

import uuid
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('tenants', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('input_json', models.JSONField(default=dict)),
                ('output_json', models.JSONField(blank=True, default=dict, null=True)),
                ('error_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='agents.agent')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tenants.environment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tenants.organization')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tools.tool')),
            ],
            options={
                'db_table': 'runs_run',
                'ordering': ['-created_at'],
            },
        ),
    ]
