# Generated by Django 5.2.8 on 2025-11-17 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_runstep'),
        ('tools', '0003_add_connection_sync_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='tool',
            field=models.ForeignKey(help_text='Tool instance', on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tools.tool'),
        ),
    ]
