# Generated by Django 5.2.8 on 2025-11-18 21:22

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_allow_empty_capabilities_tags'),
        ('runs', '0003_alter_run_tool'),
        ('tenants', '0003_organizationmembership'),
        ('tools', '0003_add_connection_sync_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(help_text="Model identifier (e.g., 'gpt-4', 'claude-3-opus')", max_length=100)),
                ('provider', models.CharField(default='openai', help_text="Provider name (e.g., 'openai', 'anthropic', 'groq')", max_length=50)),
                ('input_cost_per_1k', models.DecimalField(decimal_places=6, help_text='Cost per 1000 input tokens in USD', max_digits=10)),
                ('output_cost_per_1k', models.DecimalField(decimal_places=6, help_text='Cost per 1000 output tokens in USD', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code (ISO 4217)', max_length=3)),
                ('effective_from', models.DateTimeField(auto_now_add=True, help_text='When this pricing becomes effective')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this pricing is currently active')),
            ],
            options={
                'db_table': 'runs_modelpricing',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddField(
            model_name='run',
            name='cost_currency',
            field=models.CharField(default='USD', help_text='Currency for cost fields', max_length=3),
        ),
        migrations.AddField(
            model_name='run',
            name='cost_input',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Cost for input tokens in USD', max_digits=12),
        ),
        migrations.AddField(
            model_name='run',
            name='cost_output',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Cost for output tokens in USD', max_digits=12),
        ),
        migrations.AddField(
            model_name='run',
            name='cost_total',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Total cost in USD (input + output)', max_digits=12),
        ),
        migrations.AddField(
            model_name='run',
            name='input_tokens',
            field=models.IntegerField(default=0, help_text='Number of input/prompt tokens consumed'),
        ),
        migrations.AddField(
            model_name='run',
            name='model_name',
            field=models.CharField(blank=True, help_text='Model used for execution (if applicable)', max_length=100),
        ),
        migrations.AddField(
            model_name='run',
            name='output_tokens',
            field=models.IntegerField(default=0, help_text='Number of output/completion tokens consumed'),
        ),
        migrations.AddField(
            model_name='run',
            name='total_tokens',
            field=models.IntegerField(default=0, help_text='Total tokens consumed (input + output)'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['organization', 'created_at'], name='runs_run_organiz_d0b82f_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['environment', 'created_at'], name='runs_run_environ_a0801f_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['agent', 'created_at'], name='runs_run_agent_i_99cee9_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['model_name', 'created_at'], name='runs_run_model_n_0143fa_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['cost_total'], name='runs_run_cost_to_1386a6_idx'),
        ),
        migrations.AddIndex(
            model_name='modelpricing',
            index=models.Index(fields=['model_name', '-effective_from'], name='runs_modelp_model_n_e76b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='modelpricing',
            index=models.Index(fields=['provider', 'model_name'], name='runs_modelp_provide_924eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='modelpricing',
            index=models.Index(fields=['is_active'], name='runs_modelp_is_acti_efb769_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modelpricing',
            unique_together={('model_name', 'effective_from')},
        ),
    ]
