# Generated by Django 5.2.8 on 2025-11-10 09:33

import django.db.models.deletion
from django.db import migrations, models


def set_existing_agents_to_runner_mode(apps, schema_editor):
    """Set mode='runner' for all existing agents."""
    Agent = apps.get_model('agents', 'Agent')
    Agent.objects.all().update(mode='runner')


def reverse_set_existing_agents_to_runner_mode(apps, schema_editor):
    """Reverse migration - no-op since we can't determine original mode."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='inbound_auth_method',
            field=models.CharField(choices=[('bearer', 'Bearer'), ('mtls', 'mTLS'), ('none', 'None')], default='bearer', max_length=20),
        ),
        migrations.AddField(
            model_name='agent',
            name='inbound_secret_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='mode',
            field=models.CharField(choices=[('runner', 'Runner'), ('caller', 'Caller')], default='runner', max_length=10),
        ),
        migrations.RunPython(
            set_existing_agents_to_runner_mode,
            reverse_set_existing_agents_to_runner_mode,
        ),
        migrations.AlterField(
            model_name='agent',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='connections.connection'),
        ),
    ]
