# Generated by Django 5.2.8 on 2025-11-11 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_accounts_se_organiz_idx_accounts_se_organiz_f359c0_idx_and_more'),
        ('agents', '0003_add_agent_mode_and_inbound_auth'),
        ('connections', '0001_initial'),
        ('tenants', '0003_organizationmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='bearer_secret_ref',
            field=models.CharField(blank=True, help_text='Secret reference for bearer token authentication', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='capabilities',
            field=models.JSONField(default=list, help_text='List of agent capabilities'),
        ),
        migrations.AddField(
            model_name='agent',
            name='default_budget_cents',
            field=models.PositiveIntegerField(default=0, help_text='Default budget in cents (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='default_max_depth',
            field=models.PositiveSmallIntegerField(default=1, help_text='Default maximum delegation depth'),
        ),
        migrations.AddField(
            model_name='agent',
            name='default_ttl_seconds',
            field=models.PositiveIntegerField(default=600, help_text='Default TTL in seconds for delegation'),
        ),
        migrations.AddField(
            model_name='agent',
            name='mtls_ca_ref',
            field=models.CharField(blank=True, help_text='Secret reference for mTLS CA certificate', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='mtls_cert_ref',
            field=models.CharField(blank=True, help_text='Secret reference for mTLS certificate', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='mtls_key_ref',
            field=models.CharField(blank=True, help_text='Secret reference for mTLS private key', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='service_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent', to='accounts.serviceaccount'),
        ),
        migrations.AddField(
            model_name='agent',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (case-insensitive unique per org/env)', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='tags',
            field=models.JSONField(default=list, help_text='Tags for filtering and grouping'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='inbound_secret_ref',
            field=models.CharField(blank=True, help_text='Secret reference for bearer token (legacy field name)', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['organization', 'environment', 'enabled'], name='agents_agen_organiz_88dddb_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['mode'], name='agents_agen_mode_bfdc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['organization', 'environment', 'slug'], name='agents_agen_organiz_e96658_idx'),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(fields=('organization', 'environment', 'slug'), name='unique_agent_slug_per_org_env'),
        ),
    ]
