# Generated by Django 5.2.8 on 2025-11-11 19:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agent_bearer_secret_ref_agent_capabilities_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='inbound_auth_method',
            field=models.CharField(choices=[('bearer', 'Bearer Token'), ('mtls', 'mTLS'), ('none', 'None')], default='bearer', max_length=20),
        ),
        migrations.AlterField(
            model_name='agent',
            name='mode',
            field=models.CharField(choices=[('runner', 'Runner'), ('delegator', 'Delegator')], default='runner', max_length=10),
        ),
        migrations.CreateModel(
            name='IssuedToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jti', models.CharField(db_index=True, help_text='JWT ID (jti claim) - unique identifier for the token', max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiration timestamp (from exp claim)')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Timestamp when token was revoked (null = active)', null=True)),
                ('scopes', models.JSONField(default=list, help_text='List of scopes granted to this token')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata (client_ip, user_agent, etc.)')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_tokens', to='agents.agent')),
                ('revoked_by', models.ForeignKey(blank=True, help_text='User who revoked the token', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agents_issuedtoken',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'revoked_at'], name='agents_issu_agent_i_e00e50_idx'), models.Index(fields=['jti'], name='agents_issu_jti_8a5551_idx'), models.Index(fields=['expires_at'], name='agents_issu_expires_54c00c_idx')],
            },
        ),
    ]
