# Generated by Django 5.2.8 on 2025-11-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_add_issued_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='mode',
            field=models.CharField(choices=[('runner', 'Runner'), ('caller', 'Caller')], default='runner', max_length=10),
        ),
    ]
