# Generated by Django 5.2.8 on 2025-11-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_fix_agent_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='capabilities',
            field=models.JSONField(blank=True, default=list, help_text='List of agent capabilities'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags for filtering and grouping'),
        ),
    ]
