# Generated by Django 5.2.8 on 2025-11-18 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_allow_empty_capabilities_tags'),
        ('tenants', '0003_organizationmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedtoken',
            name='environment',
            field=models.ForeignKey(blank=True, help_text='Environment this token is valid for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_tokens', to='tenants.environment'),
        ),
        migrations.AddField(
            model_name='issuedtoken',
            name='issued_to',
            field=models.ForeignKey(blank=True, help_text='User who created this token', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_issued_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuedtoken',
            name='last_used_at',
            field=models.DateTimeField(blank=True, help_text='Last time this token was used for authentication', null=True),
        ),
        migrations.AddField(
            model_name='issuedtoken',
            name='name',
            field=models.CharField(blank=True, help_text="User-friendly name for this token (e.g., 'My Claude Desktop Token')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issuedtoken',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this token belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_tokens', to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='issuedtoken',
            name='purpose',
            field=models.CharField(choices=[('claude-desktop', 'Claude Desktop'), ('api', 'API Integration'), ('development', 'Development'), ('ci-cd', 'CI/CD')], default='api', help_text='Purpose/use case for this token', max_length=50),
        ),
        migrations.AddField(
            model_name='issuedtoken',
            name='use_count',
            field=models.IntegerField(default=0, help_text='Number of times this token has been used'),
        ),
        migrations.AlterField(
            model_name='issuedtoken',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_tokens', to='agents.agent'),
        ),
        migrations.AddIndex(
            model_name='issuedtoken',
            index=models.Index(fields=['organization', 'revoked_at'], name='agents_issu_organiz_323d11_idx'),
        ),
        migrations.AddIndex(
            model_name='issuedtoken',
            index=models.Index(fields=['purpose'], name='agents_issu_purpose_aabf17_idx'),
        ),
    ]
