# Generated by Django 5.2.8 on 2025-11-10 21:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_organizationmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('input_schema', models.JSONField(default=dict, help_text='JSON Schema for prompt input variables')),
                ('template_system', models.TextField(blank=True, help_text='System message template (Jinja2)')),
                ('template_user', models.TextField(blank=True, help_text='User message template (Jinja2)')),
                ('uses_resources', models.JSONField(default=list, help_text='List of resource names used by this prompt')),
                ('output_hints', models.JSONField(blank=True, default=dict, help_text='Hints for expected output format')),
                ('enabled', models.BooleanField(default=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='tenants.environment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='tenants.organization')),
            ],
            options={
                'db_table': 'mcp_ext_prompt',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'environment', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('static', 'Static'), ('http', 'HTTP'), ('sql', 'SQL'), ('s3', 'S3'), ('file', 'File')], default='static', max_length=20)),
                ('config_json', models.JSONField(default=dict, help_text='Configuration for resource type (e.g., URL for HTTP, value for static)')),
                ('mime_type', models.CharField(default='application/json', help_text='MIME type of the resource content', max_length=80)),
                ('schema_json', models.JSONField(blank=True, help_text='JSON Schema describing the resource structure', null=True)),
                ('secret_ref', models.CharField(blank=True, help_text='Secret reference for authentication (e.g., API keys)', max_length=255, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='tenants.environment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='tenants.organization')),
            ],
            options={
                'db_table': 'mcp_ext_resource',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'environment', 'name')},
            },
        ),
    ]
