# Generated by Django 5.2.8 on 2025-11-18 20:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_ext', '0001_initial'),
        ('tenants', '0003_organizationmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPServerRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Human-readable name (e.g., 'GitHub MCP Server')", max_length=255)),
                ('slug', models.SlugField(help_text="Unique identifier for Claude Desktop config (e.g., 'github')", max_length=64)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this server provides')),
                ('server_type', models.CharField(choices=[('stdio', 'stdio (native)'), ('http', 'HTTP-based'), ('ws', 'WebSocket')], default='http', help_text='Transport protocol for MCP communication', max_length=10)),
                ('endpoint', models.URLField(blank=True, help_text="For HTTP/WS servers: full URL (e.g., 'https://api.github.com/mcp')", max_length=500)),
                ('command', models.CharField(blank=True, help_text="For stdio servers: executable command (e.g., 'npx', 'python')", max_length=500)),
                ('args', models.JSONField(default=list, help_text="Command arguments as array (e.g., ['-y', '@modelcontextprotocol/server-github'])")),
                ('env_vars', models.JSONField(default=dict, help_text="Environment variables for stdio servers (e.g., {'GITHUB_TOKEN': 'secret://github-token'})")),
                ('auth_method', models.CharField(choices=[('none', 'No Authentication'), ('bearer', 'Bearer Token'), ('basic', 'Basic Auth'), ('api_key', 'API Key'), ('oauth2', 'OAuth2')], default='none', help_text='Authentication method for HTTP/WS servers', max_length=20)),
                ('secret_ref', models.CharField(blank=True, help_text="Reference to secret in SecretStore (e.g., 'github-pat')", max_length=255)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this server is active and available for use')),
                ('last_health_check', models.DateTimeField(blank=True, help_text='Last time a health check was performed', null=True)),
                ('health_status', models.CharField(default='unknown', help_text='Current health status (unknown/healthy/unhealthy)', max_length=20)),
                ('health_message', models.TextField(blank=True, help_text='Details from last health check')),
                ('tags', models.JSONField(default=list, help_text="Tags for categorization (e.g., ['development', 'external'])")),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata (e.g., version, capabilities)')),
                ('environment', models.ForeignKey(help_text='Environment this server is available in', on_delete=django.db.models.deletion.CASCADE, related_name='mcp_servers', to='tenants.environment')),
                ('organization', models.ForeignKey(help_text='Organization that owns this MCP server', on_delete=django.db.models.deletion.CASCADE, related_name='mcp_servers', to='tenants.organization')),
            ],
            options={
                'db_table': 'mcp_ext_server_registration',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'environment', 'enabled'], name='mcp_ext_ser_organiz_67bc75_idx'), models.Index(fields=['slug'], name='mcp_ext_ser_slug_eea3fd_idx'), models.Index(fields=['server_type'], name='mcp_ext_ser_server__a32ef6_idx')],
                'unique_together': {('organization', 'environment', 'slug')},
            },
        ),
    ]
