# Generated by Django 5.2.8 on 2025-11-19 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_ext', '0003_mcphubserver'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mcphubserver',
            new_name='mcp_ext_hub_full_na_faf168_idx',
            old_name='mcp_ext_hu_full_na_idx',
        ),
        migrations.RenameIndex(
            model_name='mcphubserver',
            new_name='mcp_ext_hub_languag_e990ec_idx',
            old_name='mcp_ext_hu_languag_idx',
        ),
        migrations.RenameIndex(
            model_name='mcphubserver',
            new_name='mcp_ext_hub_stargaz_a966f4_idx',
            old_name='mcp_ext_hu_stargaz_idx',
        ),
        migrations.RenameIndex(
            model_name='mcphubserver',
            new_name='mcp_ext_hub_is_acti_622e33_idx',
            old_name='mcp_ext_hu_is_acti_idx',
        ),
    ]
