# Generated by Django 5.2.8 on 2025-11-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('tenants', '0003_organizationmembership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevent',
            options={'ordering': ['-ts', '-created_at']},
        ),
        migrations.AddField(
            model_name='auditevent',
            name='action',
            field=models.CharField(blank=True, help_text="Action performed, e.g., 'tool.invoke', 'agent.invoke'", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='context',
            field=models.JSONField(default=dict, help_text='Additional context for the audit event'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='decision',
            field=models.CharField(blank=True, choices=[('allow', 'Allow'), ('deny', 'Deny')], help_text='Policy decision: allow or deny', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='rule_id',
            field=models.IntegerField(blank=True, help_text='ID of the matching policy rule (if any)', null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='subject',
            field=models.CharField(blank=True, help_text='Calling identity (Agent/User/Client)', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='target',
            field=models.CharField(blank=True, help_text="Target of the action, e.g., 'tool:pdf/read', 'agent:ocr'", max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='ts',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the event (synced with created_at)', null=True),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['subject', 'action', 'decision'], name='audit_audit_subject_e1e1c3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['ts'], name='audit_audit_ts_db3712_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organization', 'ts'], name='audit_audit_organiz_a16f05_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['rule_id'], name='audit_audit_rule_id_e7b9a7_idx'),
        ),
    ]
