# Generated by Django 5.2.8 on 2025-11-09 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_alter_policy_created_at_alter_policy_id'),
        ('tenants', '0002_environment_updated_at_organization_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='tenants.environment'),
        ),
    ]
