# Generated by Django 5.2.8 on 2025-11-11 10:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_policy_enabled_policy_environment'),
        ('tenants', '0003_organizationmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_type', models.CharField(choices=[('org', 'Organization'), ('env', 'Environment'), ('agent', 'Agent'), ('tool', 'Tool'), ('role', 'Role'), ('user', 'User'), ('resource_ns', 'Resource Namespace')], help_text='Scope type: org, env, agent, tool, role, user, resource_ns', max_length=24)),
                ('scope_id', models.CharField(help_text='Scope identifier: UUID, slug, or path', max_length=64)),
                ('priority', models.IntegerField(default=100, help_text='Priority: smaller number = more specific (evaluated first)')),
            ],
            options={
                'db_table': 'policies_policybinding',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(help_text='Action type, e.g., "tool.invoke", "agent.invoke", "resource.read", "resource.write"', max_length=64)),
                ('target', models.CharField(help_text='Target pattern, e.g., "tool:pdf/*", "agent:ocr", "resource:minio://org/env/path/*"', max_length=256)),
                ('effect', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], help_text='Effect: allow or deny', max_length=8)),
                ('conditions', models.JSONField(default=dict, help_text='Conditions: env==, time_window, tags contains, risk_level<=, content_type in, max_size_mb<=, allowed_tools, allowed_resource_ns')),
            ],
            options={
                'db_table': 'policies_policyrule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='policy',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['organization', 'is_active'], name='policies_po_organiz_1799ea_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['organization', 'environment', 'is_active'], name='policies_po_organiz_b6ea0b_idx'),
        ),
        migrations.AddField(
            model_name='policybinding',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='policies.policy'),
        ),
        migrations.AddField(
            model_name='policyrule',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='policies.policy'),
        ),
        migrations.AddIndex(
            model_name='policybinding',
            index=models.Index(fields=['scope_type', 'scope_id', 'priority'], name='policies_po_scope_t_f6816c_idx'),
        ),
        migrations.AddIndex(
            model_name='policybinding',
            index=models.Index(fields=['policy', 'scope_type'], name='policies_po_policy__b4b5ed_idx'),
        ),
        migrations.AddIndex(
            model_name='policyrule',
            index=models.Index(fields=['policy', 'action'], name='policies_po_policy__0091ef_idx'),
        ),
        migrations.AddIndex(
            model_name='policyrule',
            index=models.Index(fields=['policy', 'effect'], name='policies_po_policy__6fd200_idx'),
        ),
    ]
