# Generated by Django 5.2.8 on 2025-11-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_policybinding_policyrule_policy_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyrule',
            name='action',
            field=models.CharField(help_text='Action type, e.g., "tool.invoke", "agent.invoke", "resource.read", "resource.write", "prompt.invoke"', max_length=64),
        ),
        migrations.AlterField(
            model_name='policyrule',
            name='target',
            field=models.CharField(help_text='Target pattern, e.g., "tool:pdf/*", "agent:ocr", "resource:minio://org/env/path/*", "prompt:customer-analysis"', max_length=256),
        ),
    ]
