# Generated by Django 5.2.8 on 2025-11-11 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_serviceaccount'),
        ('tenants', '0003_organizationmembership'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='serviceaccount',
            new_name='accounts_se_organiz_f359c0_idx',
            old_name='accounts_se_organiz_idx',
        ),
        migrations.RenameIndex(
            model_name='serviceaccount',
            new_name='accounts_se_audienc_5c313b_idx',
            old_name='accounts_se_audienc_idx',
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='credential_ref',
            field=models.CharField(blank=True, help_text='Path in SecretStore for credentials', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiration timestamp', null=True),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='rotated_at',
            field=models.DateTimeField(blank=True, help_text='Last credential rotation timestamp', null=True),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='subject',
            field=models.CharField(blank=True, help_text='Subject identifier, e.g., "agent:ingest@org/env"', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='audience',
            field=models.CharField(help_text='Canonical MCP URI for audience validation', max_length=255),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_accounts', to='tenants.environment'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='issuer',
            field=models.CharField(help_text='Expected issuer (iss) claim in tokens', max_length=255),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_accounts', to='tenants.organization'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='scope_allowlist',
            field=models.JSONField(default=list, help_text='List of allowed scopes. Empty list means all scopes are allowed.'),
        ),
        migrations.AddIndex(
            model_name='serviceaccount',
            index=models.Index(fields=['subject'], name='accounts_se_subject_7dfb1d_idx'),
        ),
    ]
