# Generated by Django 5.2.8 on 2025-11-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_accounts_se_organiz_idx_accounts_se_organiz_f359c0_idx_and_more'),
        ('tenants', '0003_organizationmembership'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceaccount',
            unique_together={('organization', 'name'), ('subject', 'issuer')},
        ),
        migrations.AddIndex(
            model_name='serviceaccount',
            index=models.Index(fields=['subject', 'issuer'], name='accounts_se_subject_d75842_idx'),
        ),
    ]
