# Generated by Django 5.2.8 on 2025-11-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_subject_issuer_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceaccount',
            name='subject',
            field=models.CharField(blank=True, help_text='Subject identifier, e.g., "agent:ingest@org/env"', max_length=255, null=True),
        ),
    ]
