# Generated by Django 5.2.8 on 2025-11-17 18:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='canvasstate',
            new_name='canvas_canv_organiz_8a67a3_idx',
            old_name='canvas_canv_organiz_idx',
        ),
        migrations.AlterField(
            model_name='canvasstate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
