# Generated by Django 5.2.8 on 2025-11-09 07:42

import uuid
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('endpoint', models.URLField(max_length=500)),
                ('auth_method', models.CharField(choices=[('none', 'None'), ('bearer', 'Bearer Token'), ('basic', 'Basic Auth')], default='none', max_length=10)),
                ('secret_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('ok', 'OK'), ('fail', 'Failed')], default='unknown', max_length=10)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='tenants.environment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='tenants.organization')),
            ],
            options={
                'db_table': 'connections_connection',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'environment', 'name')},
            },
        ),
    ]
