# Generated by Django 5.2.8 on 2025-11-09 16:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredSecret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ref', models.CharField(db_index=True, max_length=500, unique=True)),
                ('encrypted_value', models.TextField()),
                ('organization_id', models.UUIDField(blank=True, null=True)),
                ('environment_id', models.UUIDField(blank=True, null=True)),
                ('key_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'secretstore_storedsecret',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ref'], name='secretstore_ref_410c56_idx'), models.Index(fields=['organization_id', 'environment_id', 'key_name'], name='secretstore_organiz_731d2b_idx')],
            },
        ),
    ]
