# Generated by Django 5.2.8 on 2025-11-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedsecret',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional expiration date for the secret', null=True),
        ),
        migrations.AddIndex(
            model_name='storedsecret',
            index=models.Index(fields=['expires_at'], name='secretstore_expires_3a443d_idx'),
        ),
    ]
